<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRoute } from 'vue-router'
import { createAdminCoupon, createAdminProduct, getAdminAuditLogs, getAdminContent, getAdminCoupons, getAdminDashboard, getAdminOrders, getAdminProducts, getAdminUsers, updateAdminContentStatus, updateAdminProductStatus, updateAdminUserStatus } from '../../api/admin'
const route = useRoute(); const loading = ref(false); const message = ref(''); const dashboard = ref<Record<string, any> | null>(null); const rows = ref<Record<string, any>[]>([]); const total = ref(0); const keyword = ref('')
const productForm = ref({ name: '', description: '', priceCents: 0, tokenAmount: 1000, stock: 100, status: 'ACTIVE' }); const couponForm = ref({ name: '', couponType: 'FIXED', discountCents: 0, minOrderCents: 0, totalCount: 0, startAt: '', endAt: '', status: 'ACTIVE' })
const currentType = computed(() => String(route.params.type ?? route.path.split('/').filter(Boolean).at(-1) ?? 'dashboard'))
const title = computed(() => ({ users: 'Users', blogs: 'Blog review', tutorials: 'Tutorial review', problems: 'Problem management', products: 'Membership products', coupons: 'Coupons', orders: 'Orders', 'audit-logs': 'Audit logs', dashboard: 'Operations overview' }[currentType.value] ?? 'Operations'))
async function load() { loading.value = true; message.value = ''; try { if (currentType.value === 'dashboard') dashboard.value = await getAdminDashboard(); else if (currentType.value === 'products') rows.value = await getAdminProducts(); else if (currentType.value === 'coupons') rows.value = await getAdminCoupons(); else if (currentType.value === 'users') { const page = await getAdminUsers({ keyword: keyword.value, page: 1, size: 20 }); rows.value = (page as any).records ?? (page as any).list ?? []; total.value = page.total } else if (currentType.value === 'orders') { const page = await getAdminOrders({ keyword: keyword.value, page: 1, size: 20 }); rows.value = (page as any).records ?? (page as any).list ?? []; total.value = page.total } else if (currentType.value === 'audit-logs') { const page = await getAdminAuditLogs({ page: 1, size: 30 }); rows.value = (page as any).records ?? (page as any).list ?? []; total.value = page.total } else { const page = await getAdminContent(currentType.value, { keyword: keyword.value, page: 1, size: 20 }); rows.value = (page as any).records ?? (page as any).list ?? []; total.value = page.total } } catch (error) { message.value = error instanceof Error ? error.message : 'Load failed' } finally { loading.value = false } }
async function toggle(row: Record<string, any>) { try { if (currentType.value === 'users') await updateAdminUserStatus(Number(row.id), Number(row.status) === 1 ? 0 : 1); else if (currentType.value === 'products') await updateAdminProductStatus(Number(row.id), row.status === 'ACTIVE' ? 'INACTIVE' : 'ACTIVE'); else if (['blogs', 'tutorials', 'problems'].includes(currentType.value)) await updateAdminContentStatus(currentType.value, Number(row.id), row.status === 'PUBLISHED' ? 'OFFLINE' : 'PUBLISHED'); else return; await load() } catch (error) { message.value = error instanceof Error ? error.message : 'Operation failed' } }
async function createProduct() { try { await createAdminProduct(productForm.value); await load() } catch (error) { message.value = error instanceof Error ? error.message : 'Create failed' } }
async function createCoupon() { try { await createAdminCoupon(couponForm.value); await load() } catch (error) { message.value = error instanceof Error ? error.message : 'Create failed' } }
onMounted(load)
</script>
<template>
  <section class="admin-page"><header class="admin-page-header"><div><p class="eyebrow">FLOWSTUDY ADMIN</p><h1>{{ title }}</h1></div><button class="primary-btn" @click="load">Refresh</button></header><p v-if="message" class="admin-message">{{ message }}</p>
    <div v-if="currentType === 'dashboard' && dashboard" class="admin-stat-grid"><article v-for="item in [{key:'users',label:'Users'},{key:'blogs',label:'Blogs'},{key:'tutorials',label:'Tutorials'},{key:'problems',label:'Problems'},{key:'orders',label:'Orders'}]" :key="item.key" class="admin-stat"><span>{{ item.label }}</span><strong>{{ dashboard[item.key]?.total ?? 0 }}</strong><small>Published/paid: {{ dashboard[item.key]?.published ?? dashboard[item.key]?.paid ?? 0 }}</small></article><article class="admin-stat"><span>Pending content</span><strong>{{ (dashboard.pendingContent?.blogs ?? 0) + (dashboard.pendingContent?.tutorials ?? 0) + (dashboard.pendingContent?.problems ?? 0) }}</strong><small>Blogs, tutorials and problems</small></article></div>
    <div v-else class="admin-card"><div v-if="currentType === 'products'" class="admin-form"><input v-model="productForm.name" placeholder="Product name" /><input v-model="productForm.priceCents" type="number" placeholder="Price cents" /><input v-model="productForm.tokenAmount" type="number" placeholder="Token amount" /><input v-model="productForm.stock" type="number" placeholder="Stock" /><button class="primary-btn" @click="createProduct">Create</button></div><div v-if="currentType === 'coupons'" class="admin-form"><input v-model="couponForm.name" placeholder="Coupon name" /><select v-model="couponForm.couponType"><option value="FIXED">Fixed</option><option value="PERCENT">Percent</option></select><input v-model="couponForm.discountCents" type="number" placeholder="Discount" /><input v-model="couponForm.totalCount" type="number" placeholder="Total count" /><input v-model="couponForm.startAt" placeholder="Start: 2026-08-23T00:00" /><input v-model="couponForm.endAt" placeholder="End: 2026-09-23T00:00" /><button class="primary-btn" @click="createCoupon">Create</button></div><div class="admin-toolbar"><input v-model="keyword" placeholder="Search" @keyup.enter="load" /><button class="secondary-btn" @click="load">Search</button><span>Total {{ total || rows.length }}</span></div><div v-if="loading" class="admin-empty">Loading...</div><div v-else-if="!rows.length" class="admin-empty">No data</div><div v-else class="admin-table-wrap"><table><thead><tr><th>ID</th><th>Name/account</th><th>Status</th><th>Created</th><th v-if="['users','blogs','tutorials','problems','products'].includes(currentType)">Action</th></tr></thead><tbody><tr v-for="row in rows" :key="row.id"><td>#{{ row.id }}</td><td>{{ row.title || row.name || row.username || row.orderNo || row.action || '-' }}</td><td><span class="admin-status">{{ row.status || row.result || '-' }}</span></td><td>{{ row.createdAt || row.created_at || '-' }}</td><td v-if="['users','blogs','tutorials','problems','products'].includes(currentType)"><button class="text-btn" @click="toggle(row)">{{ row.status === 'PUBLISHED' || row.status === 'ACTIVE' || Number(row.status) === 1 ? 'Disable' : 'Enable' }}</button></td></tr></tbody></table></div></div>
  </section>
</template>
